trigger:
  branches:
    include:
      - master
  paths:
    include:
      - OMLSampleCodeTest/*
    exclude:
      - OMLSampleCodeTest/README.md
      - OMLSampleCodeTest/.azure-pipelines/*
      - OMLSampleCodeTest/.gitignore
      - OMLSampleCodeTest/.vscode/*

jobs:
- job: Build_Test_Publish
  timeoutInMinutes: 20
  pool:
    vmImage: vs2017-win2016
  variables:
    projectName: OMLSampleCodeTest
    projectDirectory: OMLSampleCodeTest
    EnableDetectorPip: true

  steps:
  - template: steps/conda-env.yml

  - template: steps/run-tests.yml

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: Component Detection

  - template: steps/package.yml

  - template: steps/code-signing.yml

  - template: steps/publish.yml